class CfgTraderCategory {
	#include "Category\Aircrafts.hpp"
	#include "Category\Ammunition.hpp"
	#include "Category\Bandit.hpp"
	#include "Category\BlackMarket.hpp"
	#include "Category\Boats.hpp"
	#include "Category\BuildingParts.hpp"
	#include "Category\CustomTraders.hpp"
	#include "Category\GeneralStores.hpp"
	#include "Category\Hero.hpp"
	#include "Category\MedicalSupplies.hpp"
	#include "Category\Metals.hpp"
	#include "Category\Weapons.hpp"
	#include "Category\Vehicles.hpp"
	#include "Category\Wholesalers.hpp"
};
