class Category_696 {
	class ItemGoldBar 			{type = "trade_items";buy[] ={100,"Coins"};sell[] ={100,"Coins"};};
	class ItemGoldBar10oz 		{type = "trade_items";buy[] ={1000,"Coins"};sell[] ={1000,"Coins"};};
	class ItemBriefcase100oz 	{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemSilverBar 		{type = "trade_items";buy[] ={1,"Coins"};sell[] ={1,"Coins"};};
	class ItemSilverBar10oz 	{type = "trade_items";buy[] ={10,"Coins"};sell[] ={10,"Coins"};};
	class ItemCopperBar10oz 	{type = "trade_items";buy[] ={1,"Coins"};sell[] ={1,"Coins"};};
	class ItemTinBar 			{type = "trade_items";buy[] ={2,"Coins"};sell[] ={2,"Coins"};};
    class ItemAluminumBar 		{type = "trade_items";buy[] ={2,"Coins"};sell[] ={2,"Coins"};};   
	class PartOre 				{type = "trade_items";buy[] ={2,"Coins"};sell[] ={2,"Coins"};};	   
	class PartOreSilver 		{type = "trade_items";buy[] ={3,"Coins"};sell[] ={3,"Coins"};};
	class PartOreGold 			{type = "trade_items";buy[] ={100,"Coins"};sell[] ={100,"Coins"};};
	class ItemTopaz 			{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemObsidian			{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemSapphire 			{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemAmethyst 			{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemEmerald 			{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemCitrine			{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
	class ItemRuby 				{type = "trade_items";buy[] ={10000,"Coins"};sell[] ={10000,"Coins"};};
};